### ISSUE TITLE
API support for Iterator

### ISSUE THREAD

**Issue by chargeflux** [scott0123/Tesseract-macOS#1]
Hi,

I really appreciate that you wrote an Obj-C wrapper for Tesseract on macOS! I am finding very useful but I was wondering if you would be open to adding more features to this API, particularly adding an iterator. The inspiration is from the [example API for Tesseract](https://github.com/tesseract-ocr/tesseract/wiki/APIExample#result-iterator-example). It doesn't seem particularly hard to implement but we would probably need to discuss on how to implement it, e.g., being its own function or an optional result for the existing function `recognize` since the flow would be very similar.

I can submit a PR if you would like to get things started.

**Comment by scott0123** [comment]
Sure, feel free to discuss that with me. Can you provide me with a use case scenario for this feature?

**Comment by chargeflux** [comment]
My particular use case is doing recognition per letter (the iterator has more options) but sometimes Tesseract's best answer is not good enough. However one of the other possible choices that Tesseract considers might be right. Tesseract doesn't normally expose the other choices because they have a lower confidence interval but I would like to expose those options through its API and manipulate so the user can do "manual" correction so to speak.

**Comment by scott0123** [comment]
I see. That would be a useful feature that we might include.
If you feel confident in writing it up yourself, feel free to do that and make a PR.
Otherwise, I'll do it when I'm free. Thanks.

**Comment by chargeflux** [comment]
I will start on the PR! Thanks for considering this.

**Comment by scott0123** [comment]
Fixed in #2
