### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by chigkim** [scott0123/Tesseract-macOS#5]
Is that possible to implement support for Swift as well? Thanks!

**Comment by scott0123** [comment]
Sorry no planned support for Swift in the foreseeable future. Labeled as wontfix.

If anyone else stumbles on this and wants to contribute swift support feel free. I have received several requests already and you can refer to this iOS version: [SwiftyTesseract](https://github.com/SwiftyTesseract/SwiftyTesseract) and it shouldn't be too hard to convert it to a OSX version.

**Comment by scott0123** [comment]
@chigkim Resolved in #7 
The README now has instructions on how to use this library in a Swift environment.
Closing this issue now.
